/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package au.id.villar.utils.beangen;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BeanProcessorTest {
/*
    @Test void someLibraryMethodReturnsTrue() {
        BeanProcessor classUnderTest = new BeanProcessor();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
*/
}
